"""add_bar_image

Revision ID: 24d9efa1b9e0
Revises: 84caf0102d68
Create Date: 2021-02-19 03:07:09.537544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d9efa1b9e0'
down_revision = '84caf0102d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bars', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bars', 'image')
    # ### end Alembic commands ###
