"""add_grades_table

Revision ID: 84caf0102d68
Revises: 86f222fa084b
Create Date: 2020-07-07 13:13:56.457180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84caf0102d68'
down_revision = '86f222fa084b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['Bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grades')
    # ### end Alembic commands ###
