"""add_bars_table

Revision ID: ec4badef9f15
Revises: b4edca4234f0
Create Date: 2020-07-03 09:08:11.298442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4badef9f15'
down_revision = 'b4edca4234f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('adress', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.String(length=150), nullable=True),
    sa.Column('longitude', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bars')
    # ### end Alembic commands ###
